### ISSUE TITLE
Not able to install Filament-Manger Plugin

### ISSUE THREAD

**Issue by Timmes123** [paukstelis/octoprint_install#10]
Hi, i used your install script for installing octoprint on ubuntu server 22.04 LTS
Everything worked fine, but i can not install Filament Manager Plugin.
The installation is working without Error, Octoprint brings a Popup with Plugin "Unknown" installed, please restart.
After Restart the Plugin don't apear in Octoprint.
I can install again, if i do it will uninstall first and install again.
I tryed Spool Manager plugin, this can not be installed.

All other Plugins i tryed are working fine

I tryed to install the plugins in an octoprint docker, there is no problem. Everything work fine.
So maybe its a Problem with the Install Script? Can somebody confirm?

**Comment by paukstelis** [comment]
Yeah, seems to be an issue with python3.9 vs 3.10: https://www.datasciencelearner.com/attributeerror-module-collections-has-no-attribute-mutablemapping/

**Comment by Timmes123** [comment]
oh sorry, my fault. thank you for reporting to the correct place :)
