### ISSUE TITLE
Camera not detected on Rock Pi 4A

### ISSUE THREAD

**Issue by Miniontab** [paukstelis/octoprint_install#12]
The script runs fine otherwise, and configures octoprint to run on my Rock Pi 4A running Debian (bullseye-stable). However, whenever I want to add my camera, the 1 minute timout runs out even though I insert my USB webcam to one of the 4 USB ports. The board itself detects my camera because a "lsusb" shows my camera in the list.

**Comment by Miniontab** [comment]
Forgot to mention that my RP4A is running Debian (bullseye-stable).

**Comment by paukstelis** [comment]
Provide the output after  doing the following:
unplug camera
`sudo dmesg -C`
plug camera in
`sudo dmesg`

**Comment by Miniontab** [comment]
`sudo dmesg -C` after unplugging camera is in [1.txt](https://github.com/paukstelis/octoprint_install/files/11476900/1.txt)
`sudo dmesg` after plugging in camera is in [2.txt](https://github.com/paukstelis/octoprint_install/files/11476904/2.txt)

**Comment by paukstelis** [comment]
based on your second file, it never assigns the camera to an input.
Because of this, the script never sees your camera. Do you have another camera to test with?

**Comment by Miniontab** [comment]
[This file](https://github.com/paukstelis/octoprint_install/files/11484777/3.txt) shows both `sudo dmesg -C` after plugging out camera and `sudo dmesg` after plugging in another one. 

I still get the same results with new camera unfortunately.

**Comment by paukstelis** [comment]
I'm not sure why it doesn't work on RockPi. There are options to setup a camera mnaually.
First verify that camera does exist as a device once you plug it in:
`ls -la /dev/video*`
You should at least have /dev/video0
Then the simplest approach is probably to use the `picam` command line option:
`sudo octoprint_install/octoprint_install.sh picam`
This will let you set up a camera, but you will need to edit the udev rules
`sudo nano /etc/udev/rules.d/99-octoprint.rules` and change `camera0` to `video0`
Then reboot.

**Comment by chrisdu** [comment]
Hello, has anyone gotten the camera to work yet? I've been trying for a few days now with no success.
Didn't work with a USB camera and with the Raspberry V1.3 and V2.1.

Hallo, hat schon jemand die Kamera zum laufen bekommen? Ich versuchs jetzt auch schon ein paar Tage ohne Erfolg.
Hab mit einer USB Camera und mit den Raspberry V1.3 und  V2.1 versuch keine funktioniert.
mit  /dev/video0*   -->
crw-rw----+ 1 root video 81, 0  3. Jun 15:45 /dev/video0
crw-rw----+ 1 root video 81, 1  3. Jun 15:45 /dev/video1
crw-rw----+ 1 root video 81, 2  3. Jun 15:45 /dev/video2
crw-rw----+ 1 root video 81, 3  3. Jun 15:45 /dev/video3
crw-rw----+ 1 root video 81, 4  3. Jun 15:45 /dev/video4
-rw-rw----  1 root video     4  3. Jun 15:45 /dev/video-dec0
-rw-rw----  1 root video     4  3. Jun 15:45 /dev/video-enc0

Octoprint camera window shows: Webcam stream not loaded...
in Octoprint Kamera Fenster erscheint: Webcamstream nicht geladen...

please help me thank you
Bitte hilf mir Danke

**Comment by paukstelis** [comment]
closing for archive
