### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by Drew3164** [paukstelis/octoprint_install#14]
git clone https://github.com/paukstelis/octoprint_install

This is asking me for user name and password?

Username for 'https://github.com':
Password for 'https://

**Comment by paukstelis** [comment]
This typically only happens when something is not spelled correctly.

**Comment by Drew3164** [comment]
Do need to put in user name and password?

**Comment by paukstelis** [comment]
No. It should just clone it.

**Comment by Drew3164** [comment]
| __ )_   _|_   _|    / ___| __ )/ |
|  _ \ | |   | |_____| |   |  _ \| |
| |_) || |   | |_____| |___| |_) | |
|____/ |_|   |_|      \____|____/|_|

Welcome to BTT-CB1 2.3.2 Bullseye with Linux 5.16.17-sun50iw9

System load:   23%              Up time:       0 min
Memory usage:  9% of 986M       IP:            192.168.100.148
CPU temp:      47°C             Usage of /:    8% of 30G

Last login: Mon May 22 14:39:50 2023 from 192.168.100.155
biqu@BTT-CB1:~$ git clone https://github.com/paukstelis/octoprint_install.git.
Cloning into 'octoprint_install.git.'...
Username for 'https://github.com':

**Comment by paukstelis** [comment]
`git clone https://github.com/paukstelis/octoprint_install`

That is all you need.

**Comment by Drew3164** [comment]
git clone https://github.com/paukstelis/octoprint_install.git.
git clone https://github.com/paukstelis/octoprint_install

No "git" on the end of your working now may wont to take that off the end on your page.

Thanks

**Comment by paukstelis** [comment]
Having git at the end is OK. the period is not.
