### ISSUE TITLE
Camera not detected, but works in KDE

### ISSUE THREAD

**Issue by unitrix0** [paukstelis/octoprint_install#15]
The script somehow doesn't detect my camera. But if I run "Kamoso" on KDE it's working fine.

Is there something special I need to do?

**Comment by paukstelis** [comment]
it may not be a v4l camera.
Do the following:
unplug camera
`sudo dmesg -C`
plug camera in
`sudo dmesg`
provide output

**Comment by unitrix0** [comment]
out put of `dmesg`
```
[ 1320.850858] usb 2-1.2: new high-speed USB device number 10 using ehci-pci
[ 1320.960954] usb 2-1.2: New USB device found, idVendor=1532, idProduct=0e05, bcdDevice= 8.21
[ 1320.960975] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 1320.960981] usb 2-1.2: Product: Razer Kiyo Pro
[ 1320.960986] usb 2-1.2: Manufacturer: Razer Inc
[ 1320.961763] usb 2-1.2: Found UVC 1.00 device Razer Kiyo Pro (1532:0e05)
[ 1320.966200] uvcvideo 2-1.2:1.1: Failed to set UVC probe control : -32 (exp. 26).
[ 1320.968835] usb 2-1.2: current rate 16000 is different from the runtime rate 48000
[ 1321.381642] usb 2-1.2: current rate 16000 is different from the runtime rate 24000
[ 1321.382695] usb 2-1.2: current rate 16000 is different from the runtime rate 32000
```

I've allowed myself to change the script a bit. I change line 365
from:
`CAM=$(dmesg | sed -n -e 's/^.*SerialNumber: //p')`
to
`CAM=$(dmesg | sed -n -e 's/^.*SerialNumber=//p')`

this detected the cam, but it still doesn't work in octoprint. It's strange since I had this camera working with the Pi version.

**Comment by paukstelis** [comment]
No, you don't want that change to script.
The script is looking for a specific input line to know where the device is associated if it does not have a true serial number.
I have seen several cases where this input line is not shown in dmesg, and I don't yet know why.
what do you have from `uname -r`?

One work around for this is to run the script with the picam command line argument and then edit the service file, as described here: https://github.com/paukstelis/octoprint_install/issues/12#issuecomment-1549445635

**Comment by paukstelis** [comment]
What distro/version is this?
`lsb_release -a`

**Comment by paukstelis** [comment]
I tried to work on this a bit. I assume there is something in kernel 6.x that is responsible. However, I fired up a tumbleweed VM, but interestingly, virtualbox assigns every device a SerialNumber, so I can't replicate a non-serial number scenario. I'll investigate more when I get additional time.

**Comment by chrisdu** [comment]
> out put of `dmesg`
> 
> ```
> [ 1320.850858] usb 2-1.2: new high-speed USB device number 10 using ehci-pci
> [ 1320.960954] usb 2-1.2: New USB device found, idVendor=1532, idProduct=0e05, bcdDevice= 8.21
> [ 1320.960975] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
> [ 1320.960981] usb 2-1.2: Product: Razer Kiyo Pro
> [ 1320.960986] usb 2-1.2: Manufacturer: Razer Inc
> [ 1320.961763] usb 2-1.2: Found UVC 1.00 device Razer Kiyo Pro (1532:0e05)
> [ 1320.966200] uvcvideo 2-1.2:1.1: Failed to set UVC probe control : -32 (exp. 26).
> [ 1320.968835] usb 2-1.2: current rate 16000 is different from the runtime rate 48000
> [ 1321.381642] usb 2-1.2: current rate 16000 is different from the runtime rate 24000
> [ 1321.382695] usb 2-1.2: current rate 16000 is different from the runtime rate 32000
> ```
> 
> I've allowed myself to change the script a bit. I change line 365 from: `CAM=$(dmesg | sed -n -e 's/^.*SerialNumber: //p')` to `CAM=$(dmesg | sed -n -e 's/^.*SerialNumber=//p')`
> 
> this detected the cam, but it still doesn't work in octoprint. It's strange since I had this camera working with the Pi version.

/ i have the same problem 
/ my out put of `dmesg`
[  725.408036] ieee80211 phy0: brcmf_run_escan: error (-52)
[  725.413411] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)
[  947.839697] brcmfmac: brcmf_sdio_bus_sleep: error while changing bus sleep st                              ate -110
[ 1331.031422] ieee80211 phy0: brcmf_run_escan: error (-52)
[ 1331.036807] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)
[ 1936.679456] ieee80211 phy0: brcmf_run_escan: error (-52)
[ 1936.684826] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)
[ 2847.902235] ieee80211 phy0: brcmf_run_escan: error (-52)
[ 2847.907617] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)
[ 3453.521424] ieee80211 phy0: brcmf_run_escan: error (-52)
[ 3453.526811] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)
[ 4059.149091] ieee80211 phy0: brcmf_run_escan: error (-52)
[ 4059.154483] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)
[ 4970.414206] ieee80211 phy0: brcmf_run_escan: error (-52)
[ 4970.419588] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)
[ 5576.023068] ieee80211 phy0: brcmf_run_escan: error (-52)
[ 5576.028488] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)
[ 6181.641585] ieee80211 phy0: brcmf_run_escan: error (-52)
[ 6181.647001] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)

**Comment by paukstelis** [comment]
> mit der Raspberry V2.1 Cam

To use Raspberry Pi Cam you must install the camera using the `picam` argument: `sudo octoprint_deploy/octoprint_deploy.sh picam`

**Comment by chrisdu** [comment]
Yes, thanks for the quick reply, but that's what I did.

**Comment by paukstelis** [comment]
> Yes, thanks for the quick reply, but that's what I did.

Then the only advice I can give you is to edit the service file and change camera0 to video0:
`sudo nano /etc/systemd/system/cam_octoprint.service`
change camera0 to video0
reboot

**Comment by chrisdu** [comment]
This is my file
[Unit]
Description=the OctoPi(buntu) webcam daemon with the user specified config
After=network.online.target
Wants=network.online.target

[Service]
User=rock
Environment="LD_LIBRARY_PATH=/home/rock/mjpg-streamer"
ExecStart=/home/rock/mjpg-streamer/mjpg_streamer -i "input_uvc.so -d /dev/cam_octoprint -r 640x480 -f 15 -tim>

[Install]
WantedBy=multi-user.target

**Comment by paukstelis** [comment]
> This is my file [Unit] Description=the OctoPi(buntu) webcam daemon with the user specified config After=network.online.target Wants=network.online.target
> 
> [Service] User=rock Environment="LD_LIBRARY_PATH=/home/rock/mjpg-streamer" ExecStart=/home/rock/mjpg-streamer/mjpg_streamer -i "input_uvc.so -d /dev/cam_octoprint -r 640x480 -f 15 -tim>
> 
> [Install] WantedBy=multi-user.target

then change /dev/cam_octoprint to /dev/video0

**Comment by chrisdu** [comment]
unfortunately after reboot and the change of stream URL
http://10.0.0.57:8002/ :8080 :8001 no picture

**Comment by paukstelis** [comment]
> unfortunately after reboot and the change of stream URL http://10.0.0.57:8002/ :8080 :8001 no picture

what is the output of the following commands:
`sudo systemctl status cam_octoprint -l --no-pager`
`ls -la /dev/video*`

**Comment by chrisdu** [comment]
Jun 03 20:37:29 rock-pi-4b-plus systemd[1]: Started the OctoPi(buntu) webcam daemon with the user specified config.
Jun 03 20:37:29 rock-pi-4b-plus systemd[371]: cam_octoprint.service: Failed to locate executable /home/rock/mjpg-streamer/mjpg_streamer: No such file or directory
Jun 03 20:37:29 rock-pi-4b-plus systemd[371]: cam_octoprint.service: Failed at step EXEC spawning /home/rock/mjpg-streamer/mjpg_streamer: No such file or directory
Jun 03 20:37:29 rock-pi-4b-plus systemd[1]: cam_octoprint.service: Main process exited, code=exited, status=203/EXEC
Jun 03 20:37:29 rock-pi-4b-plus systemd[1]: cam_octoprint.service: Failed with result 'exit-code'.
Warning: The unit file, source configuration file or drop-ins of cam_octoprint.service changed on disk. Run 'systemctl daemon-reload' to reload units.
crw-rw----+ 1 root video 81, 0  3. Jun 20:37 /dev/video0
crw-rw----+ 1 root video 81, 1  3. Jun 20:37 /dev/video1
crw-rw----+ 1 root video 81, 2  3. Jun 20:37 /dev/video2
crw-rw----+ 1 root video 81, 3  3. Jun 20:37 /dev/video3
crw-rw----+ 1 root video 81, 4  3. Jun 20:37 /dev/video4
crw-rw----+ 1 root video 81, 8  3. Jun 20:37 /dev/video5
crw-rw----+ 1 root video 81, 9  3. Jun 20:37 /dev/video6
-rw-rw----  1 root video     4  3. Jun 20:37 /dev/video-dec0
-rw-rw----  1 root video     4  3. Jun 20:37 /dev/video-enc0

**Comment by paukstelis** [comment]
mjpg-streamer was not installed.

`cd; git clone https://github.com/jacksonliam/mjpg-streamer.git mjpeg`
`make -C mjpeg/mjpg-streamer-experimental`
`mv mjpeg/mjpg-streamer-experimental /home/$USER/mjpg-streamer`

**Comment by chrisdu** [comment]
als root installieren?

**Comment by unitrix0** [comment]
I gave up and switched to the docker image

**Comment by chrisdu** [comment]
rock@rock-pi-4b-plus:~$ sudo systemctl status cam_octoprint -l --no-pager
ls -la /dev/video*
* cam_octoprint.service - the OctoPi(buntu) webcam daemon with the user specified config
     Loaded: loaded (/etc/systemd/system/cam_octoprint.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-06-03 20:48:19 CEST; 8min ago
    Process: 363 ExecStart=/home/rock/mjpg-streamer/mjpg_streamer -i input_uvc.so -d /dev/video0 -r 640x480 -f 15 -timeout 30 -o output_http.so -p 8001 (code=exited, status=203/EXEC)
   Main PID: 363 (code=exited, status=203/EXEC)
        CPU: 7ms

Jun 03 20:48:19 rock-pi-4b-plus systemd[1]: Started the OctoPi(buntu) webcam daemon with the user specified config.
Jun 03 20:48:19 rock-pi-4b-plus systemd[363]: cam_octoprint.service: Failed to locate executable /home/rock/mjpg-streamer/mjpg_streamer: No such file or directory
Jun 03 20:48:19 rock-pi-4b-plus systemd[363]: cam_octoprint.service: Failed at step EXEC spawning /home/rock/mjpg-streamer/mjpg_streamer: No such file or directory
Jun 03 20:48:19 rock-pi-4b-plus systemd[1]: cam_octoprint.service: Main process exited, code=exited, status=203/EXEC
Jun 03 20:48:19 rock-pi-4b-plus systemd[1]: cam_octoprint.service: Failed with result 'exit-code'.
crw-rw----+ 1 root video 81, 0  3. Jun 20:48 /dev/video0
crw-rw----+ 1 root video 81, 1  3. Jun 20:48 /dev/video1
crw-rw----+ 1 root video 81, 2  3. Jun 20:48 /dev/video2
crw-rw----+ 1 root video 81, 3  3. Jun 20:48 /dev/video3
crw-rw----+ 1 root video 81, 4  3. Jun 20:48 /dev/video4
crw-rw----+ 1 root video 81, 8  3. Jun 20:48 /dev/video5
crw-rw----+ 1 root video 81, 9  3. Jun 20:48 /dev/video6
-rw-rw----  1 root video     4  3. Jun 20:48 /dev/video-dec0
-rw-rw----  1 root video     4  3. Jun 20:48 /dev/video-enc0

**Comment by chrisdu** [comment]
> I gave up and switched to the docker image

Hello, 
can I get a docker image on the rock pi or how does it work? 
Unfortunately I'm a beginner.
maybe you can help me with that

danke

**Comment by paukstelis** [comment]
Docker discussion can go elsewhere. I am closing this.
