### ISSUE TITLE
cam_octoprint service not starting because ustreamer executable doesn't exist

### ISSUE THREAD

**Issue by lukew3** [paukstelis/octoprint_install#16]
I used the install script, selected ustreamer when asked, and set up a camera. However, octoprint couldnt find the stream, so I checked the cam_octoprint status and saw this:

![PXL_20230530_193944750~2.jpg](https://github.com/paukstelis/octoprint_install/assets/47042841/c5b6c901-7a7c-4130-a7e9-55b1713f8cf9)

Ustreamer was not present in my home directory, so to get this to work, I had to git clone ustreamer into my home directory, build it, and restart the cam_octoprint service.

**Comment by paukstelis** [comment]
That happens occasionally. A newer version of an installation script I am working on will have checks to make sure it downloads and builds.
