### ISSUE TITLE
Elegoo Neptune 3 Plus not show up for USB

### ISSUE THREAD

**Issue by pennakira** [paukstelis/octoprint_install#19]
Thank you for the links, everything works great with my Rostock Max v2 3d Printing. I am having trouble getting my Elegoo Neptune 3 Plus to connect my printer and the cable works on Octoprint on Windows. Not on Pi Os running on a Windows Surface RT with OctoPrint. I think it is because the drivers are missing, the device is listed in lbusb. Any help would be great. thank you

**Comment by paukstelis** [comment]
you can provide some more information by doing the following:
`sudo dmesg -C`
plug printer in to USB
`sudo dmesg`
provide output.

**Comment by paukstelis** [comment]
did you plug the printer in between dmesg -C and the next dmesg?

**Comment by pennakira** [comment]
maxv2@raspberrypi:~ $ sudo dmesg -C
maxv2@raspberrypi:~ $ sudo dmesg
[ 1469.784784] usb 1-1: new full-speed USB device number 4 using ci_hdrc

**Comment by paukstelis** [comment]
Then this is a case where the linux kernel is not detecting the device correctly. It may be that you need to install drivers, as you suggested.

**Comment by pennakira** [comment]
ch341 linux serial driver
Description
​ USB serial driver for USB to UART chip ch340, ch341, etc. In fact Linux mainline kernels have built-in ch341 serial driver since kernel version 2.6.24. The location is: drivers/usb/serial/ch341.c, it's a pity that the built-in driver cannot be kept up to date. We suggest our customers use this driver.

Open "Terminal"
Switch to "driver" directory
Compile the driver using "make", you will see the module "ch341.ko" if successful
Type "sudo make load" or "sudo insmod ch341.ko" to load the driver dynamically
Type "sudo make unload" or "sudo rmmod ch341.ko" to unload the driver
Type "sudo make install" to make the driver work permanently
Type "sudo make uninstall" to remove the driver
You can refer to the link below to acquire uart application, you can use gcc or Cross-compile with cross-gcc https://github.com/WCHSoftGroup/tty_uart

**Comment by pennakira** [comment]
this is the out put for the command "make" from above

maxv2@raspberrypi:~/ch341ser_linux/driver $ make
make -C /lib/modules/5.17.0-rc3-next-20220207-g5bd2d473f01f/build  M=/home/maxv2/ch341ser_linux/driver
make[1]: *** /lib/modules/5.17.0-rc3-next-20220207-g5bd2d473f01f/build: No such file or directory.  Stop.
make: *** [Makefile:5: default] Error 2

**Comment by pennakira** [comment]
I am having no luck installing the driver, any help? thank you

**Comment by paukstelis** [comment]
Sorry, that's beyond the scope of support I can provide. I would contact the printer manufacturer.

**Comment by pennakira** [comment]
Thank you for the help

**Comment by paukstelis** [comment]
closing for archive
