### ISSUE TITLE
Changing camera settings after install

### ISSUE THREAD

**Issue by darthtate** [paukstelis/octoprint_install#2]
My camera keeps freezing and causing high cpu usage when I run Octoprint after using your installer. How can I go back and change the resolution and fps settings?

**Comment by paukstelis** [comment]
edit the service file: `sudo nano /etc/systemd/system/cam_octoprint.service`

**Comment by darthtate** [comment]
That was what I needed. Works perfect now. Thanks! And thanks for creating this install setup. I am pretty new to linux and this was a HUGE help!
