### ISSUE TITLE
Filament Manger fails to install

### ISSUE THREAD

**Issue by wizardkitty** [paukstelis/octoprint_install#22]
Filament Manager is pretty much abandoned and due to that some updates to programs have started to cause issues making installing filament manager from the repository impossible on some systems but as software is updated more systems will be unable to install it.

I have found a working version however at [](https://github.com/bitsy-ai/OctoPrint-FilamentManager/tree/fix-python-10-compat) and it works fine.

**Comment by paukstelis** [comment]
closing for archive
