### ISSUE TITLE
snapshot url

### ISSUE THREAD

**Issue by skl111** [paukstelis/octoprint_install#3]
I am trying to use obico which uses the snapshot url, and using /cam_octoprint/?action=snapshot does not work for the URL.

**Comment by apphead** [comment]
Same here. Neither snapshot or stream work. ustreamer with haproxy on OctoPi

During setup, the script ends in a loop: Add USB Camera works, then after OctoPrint restart - yes or no does not matter with respect to the outcome - it keeps asking me to Add USB Camera again. Quit does what it says. I feel the installation process is aborted at that point which breaks the webcam support.

**Comment by paukstelis** [comment]
> Same here. Neither snapshot or stream work. ustreamer with haproxy on OctoPi
> 
> During setup, the script ends in a loop: Add USB Camera works, then after OctoPrint restart - yes or no does not matter with respect to the outcome - it keeps asking me to Add USB Camera again. Quit does what it says. I feel the installation process is aborted at that point which breaks the webcam support.

It doesn't keep asking you to add the usb camera it is just repeating the menu you have already used.

**Comment by paukstelis** [comment]
> 

I do not expect that path would work, and that  is not the path set by the script. It does not set relative paths for snapshots. obico makes modifications to the snapshot path if I recall. You should reach out to them for support if their modifications are not working on your system.

**Comment by apphead** [comment]
> > Same here. Neither snapshot or stream work. ustreamer with haproxy on OctoPi
> > During setup, the script ends in a loop: Add USB Camera works, then after OctoPrint restart - yes or no does not matter with respect to the outcome - it keeps asking me to Add USB Camera again. Quit does what it says. I feel the installation process is aborted at that point which breaks the webcam support.
> 
> It doesn't keep asking you to add the usb camera it is just repeating the menu you have already used.

What am I supposed to then? Quit and call it a day?

I just setup octoprint from scratch/command line and get a 404 for the stream no matter what URL I use. Maybe it's  haproxy?

**Comment by paukstelis** [comment]
Look, cameras are a pain. I've tried to simplify the process as much as possible but there are subtle differences in hardware that make it virtually impossible to know why certain things don't work on each system. The best place for support is to join the discord server linked in README, or go to the OctoPrint discord server/forums and ask there.

**Comment by skl111** [comment]
> > 
> 
> I do not expect that path would work, and that is not the path set by the script. It does not set relative paths for snapshots. obico makes modifications to the snapshot path if I recall. You should reach out to them for support if their modifications are not working on your system.

Can you have it set relative paths for the snapshots, that might fix it as obico is just looking for a valid path, its not trying to modify it.

**Comment by apphead** [comment]
OK, thanks @paukstelis appreciated. Cams are a pain (even tho I have zero issues with the same model, running Mainsail / Klipper) works like a charm.
I am no Linux native but a patient tinkerer ;-) and I believe I have narrowed down my problem to the haproxy. No matter what I do it just fails to start.
Followed instructions here https://3dprintscape.com/install-octoprint-on-linux/

```
sudo service haproxy status
● haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/lib/systemd/system/haproxy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2023-02-02 14:18:56 GMT; 4min 37s ago
     Docs: man:haproxy(1)
           file:/usr/share/doc/haproxy/configuration.txt.gz
  Process: 1216 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS (code=exited, status=1/FAIL

Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: haproxy.service: Service RestartSec=100ms expired, schedulin
Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: haproxy.service: Scheduled restart job, restart counter is a
Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: Stopped HAProxy Load Balancer.
Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: haproxy.service: Start request repeated too quickly.
Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: haproxy.service: Failed with result 'exit-code'.
Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: Failed to start HAProxy Load Balancer.
```
checked haproxy log files, no clues there. I'm at my wits (and patience) end.

**Comment by paukstelis** [comment]
> OK, thanks @paukstelis appreciated. Cams are a pain (even tho I have zero issues with the same model, running Mainsail / Klipper) works like a charm. I am no Linux native but a patient tinkerer ;-) and I believe I have narrowed down my problem to the haproxy. No matter what I do it just fails to start. Followed instructions here https://3dprintscape.com/install-octoprint-on-linux/
> 
> ```
> sudo service haproxy status
> ● haproxy.service - HAProxy Load Balancer
>    Loaded: loaded (/lib/systemd/system/haproxy.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Thu 2023-02-02 14:18:56 GMT; 4min 37s ago
>      Docs: man:haproxy(1)
>            file:/usr/share/doc/haproxy/configuration.txt.gz
>   Process: 1216 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS (code=exited, status=1/FAIL
> 
> Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: haproxy.service: Service RestartSec=100ms expired, schedulin
> Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: haproxy.service: Scheduled restart job, restart counter is a
> Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: Stopped HAProxy Load Balancer.
> Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: haproxy.service: Start request repeated too quickly.
> Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: haproxy.service: Failed with result 'exit-code'.
> Feb 02 14:18:56 PrusaMK3S-RPi systemd[1]: Failed to start HAProxy Load Balancer.
> ```
> 
> checked haproxy log files, no clues there. I'm at my wits (and patience) end.

Did you do any hand modifications to haproxy.cfg?

what do you have in the file: `cat /etc/haproxy/haproxy.cfg`

**Comment by apphead** [comment]
Thank you so much for taking your time!!! I am about to lose my sanity over this °§@#°¢§
```
global
  log /dev/log  local0
  log /dev/log  local1 notice
  chroot /var/lib/haproxy
  stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
  stats timeout 30s
  user haproxy
  group haproxy
  daemon

defaults
  log  global
  mode  tcp
  option  tcplog
  option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http
  
frontend public
        bind *:80
        use_backend webcam if { path_beg /webcam/ }
        default_backend octoprint

backend octoprint
        mode http
        option forwardfor
        server octoprint1 127.0.0.1:5000

backend webcam
	mode http
        #http-request replace-path /webcam/(.*) /\1
        reqrep ^([^\ :]*)\ /webcam/(.*)     \1\ /\2
        server webcam1  127.0.0.1:8080
```
about backend webcam: had to comment out replace-path as it gave me a warning:

`[ALERT] 032/153354 (3742) : parsing [/etc/haproxy/haproxy.cfg:38]: 'http-request' expects 'allow', 'deny', 'auth', 'redirect', 'tarpit', 'add-header', 'set-header', 'replace-header', 'replace-value', 'set-nice', 'set-tos', 'set-mark', 'set-log-level', 'add-acl', 'del-acl', 'del-map', 'set-map', 'track-sc*', 'wait-for-handshake', 'capture', 'reject', 'set-method', 'set-path', 'set-query', 'set-uri', 'use-service', 'send-spoe-group', 'sc-inc-gpc0(*)', 'sc-set-gpt0(*)', 'silent-drop', 'set-src', 'set-src-port', 'set-dst', 'set-dst-port', 'cache-use', 'set-var(*)', 'unset-var(*)', but got 'replace-path'.`

And replaced it with reqrep. Now the config is valid ( haproxy -f  /etc/haproxy/haproxy.cfg -c)

Tried to update haproxy to 2.2, that's another failure.

OctoPrint is running, but http://prusamk3s-rpi/webcam/?action=stream returns 404

So, yeah I am totally stuck. I spent half my day trying to figure it out....

**Comment by paukstelis** [comment]
So it looks like you are using OctoPi, which means there was really no reason to use the octoprint_install script (if you did in fact use it). The contents you have there will not work with haproxy 2.2, which is likely the source of the error. Why not start fresh with reflashing OctoPi?

**Comment by apphead** [comment]
Nah, I started from scratch with latest Raspian Lite image.

**Comment by skl111** [comment]
I thought the fix would be complicated, but its simple, maybe you can add this when the webcam is added, currently the snapshot url is populated with the hostname of the system, instead of localhost, which fixes the issue.

**Comment by skl111** [comment]
> > I thought the fix would be complicated, but its simple, maybe you can add this when the webcam is added, currently the snapshot url is populated with the hostname of the system, instead of localhost, using local host fixes the issue
> 
> Thanks for your advice. Prepended my paths with http://localhost/ -> snapshot ok, stream not found????

http://localhost:8001?action=snapshot

**Comment by apphead** [comment]
Just did a fresh install of OctoPi, restored my backup and have the same effing problem. So no webcam for me then. Pitty. Klipper UI is just so much more **working**

![image](https://user-images.githubusercontent.com/505490/216432976-b9131cc9-fe19-40af-aa45-3d4b05985cc8.png)

Oh, crap

**Comment by apphead** [comment]
Proxy seems to be functional. Yaaai!
![image](https://user-images.githubusercontent.com/505490/216434299-93e0f977-642e-4962-b62c-a6cb9bc77a52.png)

**Comment by apphead** [comment]
WTF: I cleared my browsers cache and voila.
CLEAR YOUR CACHE - on the client-side.

**Comment by apphead** [comment]
Just for the record: same caching issue re-appeared again shortly after. Loading stream takes forever (tested on latest Brave and Firefox browsers).
Uncommented define STD_HEADER  in /home/pi/mjpg-streamer/plugins/output_http/httpd.h
I am not sure this makes a difference at that point, but it seems to be working reliably now. Case closed for me.

**Comment by skl111** [comment]
@paukstelis I would suggest adding a note in the readme for the snapshot url needing to be changed or have a script change it, as with or without obico it doesn't work until its changed from the default which is the hostname to using localhost with HAproxy enabled in my case.

**Comment by plano-harry** [comment]
I did not select HAproxy and still have the install loop issue on a Quadra host.  Tried USB 2 and USB 3 port.

**Comment by paukstelis** [comment]
> I did not select HAproxy and still have the install loop issue on a Quadra host. Tried USB 2 and USB 3 port.

I have no idea what you mean by 'install loop issue`

**Comment by skl111** [comment]
@paukstelis this issue is solved  by using localhost (4 different machines, so you can close it, though I would suggest adding a note.

**Comment by plano-harry** [comment]
@paukstelis sorry, I was referring to the camera install loop issue.  I did not choose haproxy, but still had the issue of not being able to recognize my USB camera in the final part of the install script.  I plugged in my camera during the 1 minute window and tried to follow the instructions, using 5 FPS (although I selected  ustreamer as the recommended streamer), then the script would loop back to install the camera again.  I have minimal knowledge of Armbian/Linux so the script was much appreciated, but I don't understand how to fix the camera install issue.

**Comment by paukstelis** [comment]
It is not a loop, the camera has just been installed and it goes back to the main menu.

**Comment by plano-harry** [comment]
@paukstelis , Thanks, I did a fresh install of the script and the camera seems to have installed.  Here is the output:
1) Add USB Camera
2) Quit
Select operation: 1
Adding USB camera
Add cameras to haproxy? [y/n]: y
Plug your camera in via USB now (detection time-out in 1 min)
Camera Serial Number not detected
Camera will be setup with physical USB address of  1-1:1.0.
The camera will have to stay plugged into this location.
Camera Port (ENTER will increment last value in /etc/camera_ports):
1
Settings can be modified after initial setup in /etc/systemd/system/cam_octoprint

Camera Resolution [default: 640x480]:
1024x768
Selected camera resolution: 1024x768
Camera Framerate (use 0 for ustreamer hardware) [default: 5]:
5
Selected camera framerate: 5
OctoPrint must restart for camera changes to take affect. Restart now? [y/n]: y
Created symlink /etc/systemd/system/multi-user.target.wants/cam_octoprint.service → /etc/systemd/system/cam_octoprint.service.
Camera installed. Exiting
---------------------------
After reboot and the camera not showing up, I looked and 
/etc/systemd/system/cam_octoprint.service  was not there.  

Can you see anything I did incorrectly?

**Comment by paukstelis** [comment]
You cannot use port 1. The default is 8001, just use that.

**Comment by plano-harry** [comment]
@paukstelis okay I have it installed on 8001 but Octoprint still doesn't see it at
http://inovato.local:8001/?action=stream
is the missing /etc/systemd/system/cam_octoprint.service not an issue?  Shouldn't it show up in that directory?

**Comment by adamesch** [comment]
thought i'd comment here since I was just having a similar problem installing octoprint onto my "le potato"

(using ubuntu w/ mjpeg-streamer, with just octoprint behind haproxy)

for me, the problems with both the stream and snapshot URLs were related to the cam_octoprint service:

<img width="822" alt="image" src="https://github.com/paukstelis/octoprint_install/assets/6181855/ff1b4981-094b-4998-8509-87a685a46b2c">

I figured out that one of the arguments `-d /dev/cam_octoprint` didn't actually exist:

<img width="523" alt="image" src="https://github.com/paukstelis/octoprint_install/assets/6181855/797b15af-4eba-402a-95e3-abef86e44dda">

I tried just editing `/etc/systemd/system/cam_octoprint.service` to point to `/dev/video1` and after reloading the file using `sudo systemctl daemon-reload` and `sudo service cam_octoprint restart` the service started successfully:

<img width="822" alt="image" src="https://github.com/paukstelis/octoprint_install/assets/6181855/47133d43-cd4d-4691-9415-667eb51c88a1">

and then after a little trial and error, I got the stream and snapshot URLs working. I used `localhost` for the snapshot URL (camera is on port 8002):

<img width="634" alt="image" src="https://github.com/paukstelis/octoprint_install/assets/6181855/6f28a11e-790f-493e-8621-3fb3516eab77">

<img width="560" alt="image" src="https://github.com/paukstelis/octoprint_install/assets/6181855/682b11b9-8948-44eb-b890-5d2d9b05cb10">

and then for the stream URL, i used the IP address of the potato (192.168.200.81):

<img width="677" alt="image" src="https://github.com/paukstelis/octoprint_install/assets/6181855/8e8d8ce4-ebfc-4432-88a0-f24767feb7b8">
<img width="557" alt="image" src="https://github.com/paukstelis/octoprint_install/assets/6181855/fc19fefd-c36f-466b-a80f-7ac98d541aa1">

maybe others are having similar problems with the cam_octoprint service? changing that one thing fixed things for me.

**Comment by jerome6994** [comment]
hello

Thank you for the installation script with support for webcams.
This allowed me to set up a VM dedicated to octoprint and free a PI3B+.

The webcam part is a little hot to set up and thanks to @adamesch for his info which allowed me to finally see the image!
On the other hand, as on the screen that I post below, I do not see the webcam on the stream of the game at the top left!
you know why ?

![image](https://github.com/paukstelis/octoprint_install/assets/66921143/ff4f076b-5241-4d13-b82b-047aa37e4331)

**Comment by abesmon** [comment]
I've got similar problem today: couldn't get stream. After 1.5 hours of investigation I figured up, that I ran install script from "Downloads" and not from my home directory, so after installation ustreamer was in the Download folder, but systemctl script awaits that streamer would be at home directory... 

```
May 31 13:47:25 orangepilite systemd[1]: Started the OctoPi(buntu) ustreamer daemon with the user specified config.
May 31 13:47:25 orangepilite systemd[1892]: cam_octoprint.service: Failed to locate executable /home/alexey/ustreamer/ustreamer: No such file or directory
May 31 13:47:25 orangepilite systemd[1892]: cam_octoprint.service: Failed at step EXEC spawning /home/alexey/ustreamer/ustreamer: No such file or directory
May 31 13:47:25 orangepilite systemd[1]: cam_octoprint.service: Main process exited, code=exited, status=203/EXEC
May 31 13:47:25 orangepilite systemd[1]: cam_octoprint.service: Failed with result 'exit-code'.
```

I've move streamer from Downloads to my home directory and everything's ok.

In the end I think  
`sudo -u $user git clone --depth=1 https://github.com/pikvm/ustreamer`

is not very safe, because it clones streamer to work directory, so if anybody run script from different directory (not from home) it would end up broken

**Comment by paukstelis** [comment]
> is not very safe, because it clones ustreamer to work directory, so if anybody run script from different directory (not from home) it would end up broken

The VERY first thing in the How to Use section of the README:  All commands assume you are operating out of your home directory using a terminal directly on the machine or by ssh

**Comment by abesmon** [comment]
true, but if there's a possibility to make script safer for users, why not to do that? :)

**Comment by paukstelis** [comment]
closing for archive
