### ISSUE TITLE
Camera snapshot and ustream 

### ISSUE THREAD

**Issue by Googliola** [paukstelis/octoprint_install#4]
During setup I get the following error:

```
The following packages have unmet dependencies:
 libjpeg-dev : Conflicts: libjpeg8-dev but 8d1-2 is to be installed
 libjpeg62-turbo-dev : Conflicts: libjpeg8-dev but 8d1-2 is to be installed
```
Dunno if this is related to my camera not working or if the problem is related to https://github.com/paukstelis/octoprint_install/issues/3#issuecomment-1413276298

**Comment by paukstelis** [comment]
What hardware and operating system are you using?

**Comment by paukstelis** [comment]
closing for archive
