### ISSUE TITLE
I can't erase backups

### ISSUE THREAD

**Issue by Vidorlp** [paukstelis/octoprint_install#6]
Hello, as I have been configuring Octoprint I have been making backups for security, now I have 6 backup that I do not need and that I would like to erase. I access the menu and in the Backup & Restore option, the backup appear but I cannot eliminate them individually or with the option of Select All. Use Debian in an old laptop. I have looked at the log and says nothing about this problem.
[octoprint.log](https://github.com/paukstelis/octoprint_install/files/10700675/octoprint.log)

Thanks

**Comment by paukstelis** [comment]
I think this should be directed to octoprint_deploy, not octoprint_install. 

Either way: `sudo rm backupfilename.tar.gz` will do it

**Comment by Vidorlp** [comment]
I'm sorry, I'm not very acquainted with github. The terminal tells me that this file does not exist, if I enter the Octoprint folder, it only appears Bin, Include, Lib, Pyvenv.cfg and Share

**Comment by Vidorlp** [comment]
I write it at Octoprint_Deploy
