### ISSUE TITLE
how do you set up a webcam after you finish setup?

### ISSUE THREAD

**Issue by for265** [paukstelis/octoprint_install#7]
I am running on a 64 bit laptop running Linux mint and I said no to the Usb webcam at initial setup but now I want to set one up but I don't know what command to use

**Comment by paukstelis** [comment]
Did you select No Streamer during the installation? What do you get with `cat /etc/octoprint_deploy`?

**Comment by for265** [comment]
I did select no streamer
and cat /etc/octoprint_deploy gave me
haproxy: true
streamer: ustreamer

**Comment by paukstelis** [comment]
that surprises me a bit that it says ustreamer in that case. What do you get with `ls -la ~/ustreamer`?

**Comment by for265** [comment]
That gave me:
total 120
drwxrwxr-x 12 e e  4096 Feb  5 15:46 .
drwxr-xr-x 24 e e  4096 Mar  7 17:17 ..
-rw-rw-r--  1 e e  1010 Feb  5 15:46 .bumpversion.cfg
-rw-rw-r--  1 e e   111 Feb  5 15:46 .dockerignore
drwxrwxr-x  2 e e  4096 Feb  5 15:46 docs
-rw-rw-r--  1 e e   121 Feb  5 15:46 .editorconfig
drwxrwxr-x  8 e e  4096 Feb  5 15:46 .git
-rw-rw-r--  1 e e   141 Feb  5 15:46 .gitattributes
drwxrwxr-x  3 e e  4096 Feb  5 15:46 .github
-rw-rw-r--  1 e e   209 Feb  5 15:46 .gitignore
drwxrwxr-x  3 e e  4096 Feb  5 15:46 janus
-rw-rw-r--  1 e e 35147 Feb  5 15:46 LICENSE
drwxrwxr-x  2 e e  4096 Feb  5 15:46 linters
-rw-rw-r--  1 e e  2362 Feb  5 15:46 Makefile
drwxrwxr-x  2 e e  4096 Feb  5 15:46 man
drwxrwxr-x  6 e e  4096 Feb  5 15:46 pkg
drwxrwxr-x  3 e e  4096 Feb  5 15:46 python
-rw-rw-r--  1 e e 11606 Feb  5 15:46 README.md
drwxrwxr-x  6 e e  4096 Feb  5 15:46 src
drwxrwxr-x  2 e e  4096 Feb  5 15:46 tools
lrwxrwxrwx  1 e e    17 Feb  5 15:46 ustreamer -> src/ustreamer.bin
lrwxrwxrwx  1 e e    22 Feb  5 15:46 ustreamer-dump -> src/ustreamer-dump.bin

**Comment by paukstelis** [comment]
This means ustreamer is installed. You should just rerun the script (sudo octoprint_install/octoprint_install.sh) and choose the 'Add USB camera' option

**Comment by for265** [comment]
well that's one step closer but now when i type in all the camera specs it gives me:
Job for haproxy.service failed because the control process exited with error code.
See "systemctl status haproxy.service" and "journalctl -xe" for details.

**Comment by paukstelis** [comment]
`cat /etc/haproxy/haproxy.cfg`
My first guess is that you have done this before and now have two entries in haproxy.

**Comment by for265** [comment]
yep but I tried checking octoprint after each try and since it didn't work i re ran it and now i have like 5 options 3 of which give a 404

**Comment by for265** [comment]
and the one with ustreamer stream just says no signal

**Comment by paukstelis** [comment]
If you select to use the cameras with haproxy and haproxy fails because you have multiple entries of the same thing, it won't work.

**Comment by paukstelis** [comment]
Can you join the Discord server? It is easier providing support there.

**Comment by for265** [comment]
found the issue the camera I was trying to use was broken and I changed it and it works now. thanks for the help!
