### ISSUE TITLE
[Suggestion] Add www-folder-path to octocam_mjpg.service

### ISSUE THREAD

**Issue by dl9sec** [paukstelis/octoprint_install#9]
Hi,

I used your script to install this OctoPrint stuff on my good old Odroid C2 running Armbian.
This works well so far. My camera also worked well with mjpg-streamer, but with Octolapse i got the problem, that I coudn't edit the cameras image preferences (things like brightness, focus, gain, sharpness, ...).

It took a while, but it was the missing "www-folder-path" (-w) in the camera systemd service. Manually set additionally "-w ./www" made at first the return of the camera parameters work (http://myIP/input.json), but the simple mjpg webinterface didnt work.

Then I set the "-w" to the full path an then all the camera settings stuff worked like a charm.

So I would suggest to set line 9 of "octocam_mjpg.service" from:

`ExecStart=/home/OCTOUSER/mjpg-streamer/mjpg_streamer -i "input_uvc.so -d /dev/OCTOCAM -r RESOLUTION -f FRAMERATE" -o "output_http.so -p CAMPORT"`

to

`ExecStart=/home/OCTOUSER/mjpg-streamer/mjpg_streamer -i "input_uvc.so -d /dev/OCTOCAM -r RESOLUTION -f FRAMERATE" -o "output_http.so -w /home/OCTOUSER/mjpg-streamer/www -p CAMPORT"`

Regards, Thorsten

**Comment by paukstelis** [comment]
closing for archive
